import 'dart:io';

import 'package:auris/auris.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'app_state.dart';
import 'dynamic_devices_view.dart';
import 'setup_wizard_view.dart';
import 'json_editor_view.dart';
import 'system_settings_view.dart';

void main() {
  runApp(
    ChangeNotifierProvider(
      create: (_) => AppStateProvider(),
      child: const RoomConfigApp(),
    ),
  );
}

class RoomConfigApp extends StatelessWidget {
  const RoomConfigApp({Key? key}) : super(key: key);

  /// The swatches offered by the Auris accent picker. Amber first (the
  /// package's canonical accent), then HUD-intensity alternates.
  static const List<Color> aurisSwatches = [
    Color(0xFFF0A500), // amber (Auris default)
    Color(0xFF35E0C0), // teal
    Color(0xFFE0409A), // magenta
    Color(0xFFE84838), // red
    Color(0xFF6AB880), // green
    Color(0xFF4FC3F7), // blue
    Color(0xFFB388FF), // violet
    Color(0xFF8AABB0), // slate
  ];

  /// The swatches offered by the Classic color picker (App Config and the
  /// first-run setup dialog). Material primaries, stored as RRGGBB hex.
  static const List<Color> classicSwatches = [
    Color(0xFFF44336), // red
    Color(0xFFE91E63), // pink
    Color(0xFF9C27B0), // purple
    Color(0xFF673AB7), // deep purple
    Color(0xFF3F51B5), // indigo
    Color(0xFF2196F3), // blue
    Color(0xFF03A9F4), // light blue
    Color(0xFF00BCD4), // cyan
    Color(0xFF009688), // teal
    Color(0xFF4CAF50), // green
    Color(0xFF8BC34A), // light green
    Color(0xFFFFC107), // amber
    Color(0xFFFF9800), // orange
    Color(0xFFFF5722), // deep orange
    Color(0xFF795548), // brown
    Color(0xFF607D8B), // blue grey
  ];

  /// Parses a stored RRGGBB hex into a Color (falls back to [fallback]).
  static Color parseHexColor(String hex,
      {Color fallback = const Color(0xFF2196F3)}) {
    final v = int.tryParse(hex, radix: 16);
    return v == null ? fallback : Color(0xFF000000 | v);
  }

  /// Resolves the active ThemeData from the Theme Style chosen in App Config
  /// ('classic' | 'auris') plus the dark/light toggle. 'classic' (the
  /// default) is a Material theme generated by flex_color_scheme around the
  /// user's chosen accent color; 'auris' is the sci-fi HUD look built around
  /// its own accent swatch. Classic also takes an optional secondary
  /// element color ('' = Auto, let the theme derive it).
  static ThemeData themeFor(String style, bool isDark, String classicColor,
      String aurisColor, String classicSecondary) {
    switch (style) {
      case 'auris':
        // The canonical amber look comes from the package default (null
        // accent) — passing the amber swatch explicitly would re-derive its
        // rungs instead of using the hand-tuned originals.
        final Color? accent = aurisColor.toUpperCase() == 'F0A500'
            ? null
            : parseHexColor(aurisColor, fallback: const Color(0xFFF0A500));
        return isDark
            ? AurisTheme.dark(accent: accent)
            : AurisTheme.light(accent: accent);
      case 'classic':
      default:
        final scheme = FlexSchemeColor.from(
          primary: parseHexColor(classicColor),
          secondary: classicSecondary.isEmpty
              ? null
              : parseHexColor(classicSecondary),
        );
        return isDark
            ? FlexThemeData.dark(colors: scheme.toDark())
            : FlexThemeData.light(colors: scheme);
    }
  }

  @override
  Widget build(BuildContext context) {
    final provider = context.watch<AppStateProvider>();

    return MaterialApp(
      // Remount the whole tree when crossing the Auris <-> Classic boundary.
      // Auris text styles use inherit: true while Classic's Material
      // defaults use inherit: false, and TextStyle.lerp throws on that
      // mismatch. themeAnimationDuration covers MaterialApp's own
      // cross-fade, but individual widgets (button labels, tab labels)
      // also animate their text styles — a remount skips every in-flight
      // animation. Auris accent changes and the dark/light toggle keep
      // the same key, so those still switch without losing UI state.
      key: ValueKey(provider.themeStyle == 'classic'),
      title: 'Deployment Configurator',
      // Style comes from App Config (Classic with a pickable accent color —
      // the default — or the Auris amber/teal/magenta variants); the
      // sun/moon toggle still switches dark <-> light within any style.
      theme: themeFor(
          provider.themeStyle,
          provider.isDarkMode,
          provider.classicColor,
          provider.aurisColor,
          provider.classicSecondary),
      themeAnimationDuration: Duration.zero,
      // App-wide text size (App Config > Text Size): scale every text style
      // by wrapping the whole app in a MediaQuery text scaler.
      builder: (context, child) => MediaQuery(
        data: MediaQuery.of(context).copyWith(
          textScaler: TextScaler.linear(provider.textScale),
        ),
        child: child!,
      ),
      home: const MainDashboard(),
    );
  }
}

class MainDashboard extends StatefulWidget {
  const MainDashboard({Key? key}) : super(key: key);

  @override
  State<MainDashboard> createState() => _MainDashboardState();
}

class _MainDashboardState extends State<MainDashboard> {
  bool _setupDialogShown = false; // Prompt at most once per app session

  @override
  Widget build(BuildContext context) {
    final provider = context.watch<AppStateProvider>();
    final hasConfig = provider.roomConfig.isNotEmpty;
    // Selected tab lives in the provider so it survives the remount that a
    // theme-family change (Auris <-> Classic) forces via the MaterialApp key.
    final int selectedIndex = provider.selectedTabIndex;

    // FIRST-RUN CHECK: once the saved settings have been read, show the
    // one-time setup dialog asking where each file is located. When setup
    // was completed on an earlier launch this is bypassed entirely.
    if (provider.settingsLoaded &&
        provider.firstRunSetupNeeded &&
        !_setupDialogShown) {
      _setupDialogShown = true;
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (!mounted) return;
        showDialog(
          context: context,
          barrierDismissible: false,
          builder: (_) => const FirstRunSetupDialog(),
        );
      });
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('Room Config Builder'),
        actions: [
          IconButton(
            icon: Icon(provider.isDarkMode ? Icons.light_mode : Icons.dark_mode),
            tooltip: 'Toggle Theme',
            onPressed: () => provider.toggleTheme(),
          ),
          IconButton(
            icon: const Icon(Icons.folder_open),
            tooltip: 'Open Existing Config',
            onPressed: () async {
              bool loaded = await provider.loadExistingConfig();
              if (loaded && provider.systemLogs.isNotEmpty && context.mounted) {
                _showMigrationLogDialog(context, provider.systemLogs);
              }
            },
          ),
          IconButton(
            icon: const Icon(Icons.cloud_download),
            tooltip: 'Download config.json from Processor (SFTP)',
            onPressed: () async {
              final result = await showDialog<bool>(
                context: context,
                barrierDismissible: false,
                builder: (context) => const ProcessorSftpDialog(isUpload: false),
              );
              // On a successful download, show the migration/audit log like a local load does
              if (result == true && provider.systemLogs.isNotEmpty && context.mounted) {
                _showMigrationLogDialog(context, provider.systemLogs);
              }
            },
          ),
          IconButton(
            icon: const Icon(Icons.cloud_upload),
            tooltip: 'Upload to Processor (SFTP)',
            onPressed: () {
              showDialog(
                context: context,
                barrierDismissible: false, 
                builder: (context) => const ProcessorSftpDialog(isUpload: true),
              );
            },
          ),
          IconButton(
            icon: const Icon(Icons.save_alt),
            tooltip: 'Export Config Locally',
            onPressed: () async {
              bool saved = await provider.exportRoomConfig();
              if (saved && context.mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('Config saved successfully!'))
                );
              }
            },
          )
        ],
      ),
      body: Row(
        children: [
          NavigationRail(
            selectedIndex: selectedIndex,
            onDestinationSelected: (int index) {
              provider.selectTab(index);
            },
            labelType: NavigationRailLabelType.all,
            destinations: const [
              NavigationRailDestination(icon: Icon(Icons.auto_awesome), label: Text('Wizard')),
              NavigationRailDestination(icon: Icon(Icons.router), label: Text('Devices')),
              NavigationRailDestination(icon: Icon(Icons.settings), label: Text('System')),
              NavigationRailDestination(icon: Icon(Icons.data_object), label: Text('Raw JSON')),
              NavigationRailDestination(icon: Icon(Icons.build_circle), label: Text('App Config')),
            ],
          ),
          const VerticalDivider(thickness: 1, width: 1),
          Expanded(
            child: (!hasConfig && selectedIndex != 4) ? _buildLandingScreen(context, provider) : _buildMainContent(selectedIndex),
          )
        ],
      ),
    );
  }

  Widget _buildLandingScreen(BuildContext context, AppStateProvider provider) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.account_tree, size: 80, color: Theme.of(context).disabledColor),
          const SizedBox(height: 24),
          Text("No Configuration Loaded", style: Theme.of(context).textTheme.headlineMedium),
          const SizedBox(height: 40),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              SizedBox(
                height: 60,
                width: 250,
                child: ElevatedButton.icon(
                  icon: const Icon(Icons.add_box),
                  label: const Text("Create New Config\n(From template)", textAlign: TextAlign.center),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blue.shade700,
                    foregroundColor: Colors.white, // Forces readable text in light mode
                  ),
                  onPressed: () async {
                    // The template path always resolves now (explicit file, else
                    // config.json in the Root Folder / working directory), so just
                    // attempt the create and report the resolved location on failure.
                    bool success = await provider.createNewConfig();
                    if (!success && context.mounted) {
                      provider.selectTab(4); // Route to App Config
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(content: Text("No template found at ${provider.effectiveTemplateFilePath}. "
                            "Place config.json there or set a Template file in App Config."), backgroundColor: Colors.red)
                      );
                    }
                  },
                ),
              ),
              const SizedBox(width: 20),
              SizedBox(
                height: 60,
                width: 250,
                child: ElevatedButton.icon(
                  icon: const Icon(Icons.folder_open),
                  label: const Text("Open Existing Config"),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.grey.shade700,
                    foregroundColor: Colors.white, // Forces readable text in light mode
                  ),
                  onPressed: () async {
                    bool loaded = await provider.loadExistingConfig();
                    if (loaded && provider.systemLogs.isNotEmpty && context.mounted) {
                      _showMigrationLogDialog(context, provider.systemLogs);
                    }
                  },
                ),
              ),
            ],
          )
        ],
      ),
    );
  }

  Widget _buildMainContent(int selectedIndex) {
    switch (selectedIndex) {
      case 0:
        return const SetupWizardView(); 
      case 1:
        return const DynamicDevicesTabsView(); 
      case 2:
        return const SystemSettingsView();
      case 3:
        return const JsonEditorView();
      case 4:
        return const AppSettingsView();
      default:
        return const Center(child: Text("Select a category"));
    }
  }
}

/// Displays a scrollable log of actions taken to make an older config compatible
void _showMigrationLogDialog(BuildContext context, List<String> logs) {
  showDialog(
    context: context,
    builder: (ctx) {
      // Theme-aware palette: keep the dark terminal feel in dark mode, use a
      // bordered light panel with high-contrast text in light mode.
      final bool isDark = Theme.of(ctx).brightness == Brightness.dark;
      final Color panelColor = isDark ? Colors.black87 : const Color(0xFFF5F5F5);
      final Color normalText = isDark ? Colors.greenAccent : Colors.green.shade800;
      final Color headerText = isDark ? Colors.orangeAccent : Colors.deepOrange.shade700;
      final Color warnText = isDark ? Colors.redAccent.shade100 : Colors.red.shade700;

      // Severity color per line so warnings stand out in the acknowledgement
      Color lineColor(String line, bool isHeader) {
        if (line.startsWith('WARNING') ||
            line.startsWith('CRITICAL') ||
            line.startsWith('COUNT WARNING') ||
            line.startsWith('FLAGGED') ||
            line.contains('SKIPPED')) {
          return warnText;
        }
        return isHeader ? headerText : normalText;
      }

      return AlertDialog(
        title: Row(
          children: [
            const Icon(Icons.warning_amber_rounded, color: Colors.orange),
            const SizedBox(width: 10),
            const Text('Legacy Config Updated'),
          ],
        ),
        content: SizedBox(
          width: 500,
          height: 300,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text("The loaded file was missing required fields for the current template. The following defaults were injected into memory:"),
              const SizedBox(height: 16),
              Expanded(
                child: Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: panelColor,
                    borderRadius: BorderRadius.circular(4),
                    border: isDark
                        ? null
                        : Border.all(color: Colors.grey.shade400), // Define the panel in light mode
                  ),
                  child: ListView.builder(
                    itemCount: logs.length,
                    itemBuilder: (context, index) {
                      bool isHeader = index == 0;
                      return Padding(
                        padding: const EdgeInsets.only(bottom: 6.0),
                        child: Text(
                          logs[index],
                          style: TextStyle(
                            fontFamily: 'monospace',
                            fontSize: 13,
                            color: lineColor(logs[index], isHeader),
                            fontWeight: isHeader ? FontWeight.bold : FontWeight.normal,
                          ),
                        ),
                      );
                    },
                  ),
                ),
              ),
              const SizedBox(height: 10),
              const Text("Note: These changes are currently only in memory. Save the config to make them permanent.", 
                style: TextStyle(fontStyle: FontStyle.italic, fontSize: 12)),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(),
            child: const Text('Acknowledge'),
          ),
        ],
      );
    },
  );
}

/// Swatch grid for a theme color. Used for the primary accent and the
/// secondary element color of both styles in App Config (and in the
/// first-run setup dialog); tapping a swatch persists it immediately and
/// the theme rebuilds live. With [allowAuto], an extra first swatch clears
/// the setting so the theme derives the color itself.
class AccentColorPicker extends StatelessWidget {
  /// Which provider setting the picker writes: 'classicColor' |
  /// 'aurisColor' | 'classicSecondary'.
  final String settingKey;
  final List<Color> swatches;
  final bool allowAuto;

  const AccentColorPicker(
      {Key? key,
      required this.settingKey,
      required this.swatches,
      this.allowAuto = false})
      : super(key: key);

  String _currentHex(AppStateProvider p) {
    switch (settingKey) {
      case 'aurisColor':
        return p.aurisColor;
      case 'classicSecondary':
        return p.classicSecondary;
      default:
        return p.classicColor;
    }
  }

  Widget _swatch(BuildContext context,
      {required bool selected,
      required VoidCallback onTap,
      Color? color,
      Widget? child}) {
    return InkWell(
      customBorder: const CircleBorder(),
      onTap: onTap,
      child: Container(
        width: 34,
        height: 34,
        decoration: BoxDecoration(
          color: color,
          shape: BoxShape.circle,
          border: selected
              ? Border.all(
                  color: Theme.of(context).colorScheme.onSurface, width: 3)
              : Border.all(color: Colors.black26),
        ),
        child: child,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final provider = context.watch<AppStateProvider>();
    final String hexNow = _currentHex(provider);
    final Color current = RoomConfigApp.parseHexColor(hexNow);

    return Wrap(
      spacing: 10,
      runSpacing: 10,
      children: [
        // AUTO: clear the setting so the theme derives this color itself
        if (allowAuto)
          Tooltip(
            message: 'Auto (theme default)',
            child: _swatch(
              context,
              selected: hexNow.isEmpty,
              onTap: () => provider.updateSetting(settingKey, ''),
              child: Icon(Icons.auto_fix_normal,
                  size: 18,
                  color: Theme.of(context).colorScheme.onSurface),
            ),
          ),
        ...swatches.map((color) {
          final bool selected =
              hexNow.isNotEmpty && color.toARGB32() == current.toARGB32();
          return _swatch(
            context,
            selected: selected,
            color: color,
            onTap: () {
              final hex = color
                  .toARGB32()
                  .toRadixString(16)
                  .toUpperCase()
                  .substring(2); // strip alpha -> RRGGBB
              provider.updateSetting(settingKey, hex);
            },
            child: selected
                ? const Icon(Icons.check, size: 18, color: Colors.white)
                : null,
          );
        }),
      ],
    );
  }
}

/// One Theme Style dropdown entry: a colored accent swatch + label.
DropdownMenuItem<String> _themeStyleItem(
    String value, String label, Color swatch) {
  return DropdownMenuItem<String>(
    value: value,
    child: Row(
      children: [
        Container(
          width: 14,
          height: 14,
          decoration: BoxDecoration(color: swatch, shape: BoxShape.circle),
        ),
        const SizedBox(width: 10),
        Text(label),
      ],
    ),
  );
}

/// View for mapping application paths and selecting the active deployment room
class AppSettingsView extends StatelessWidget {
  const AppSettingsView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final provider = context.watch<AppStateProvider>();

    return ListView(
      padding: const EdgeInsets.all(32.0),
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text('Application Configuration', style: Theme.of(context).textTheme.headlineMedium),
            // Re-opens the same dialog shown on the very first launch, for
            // fixing paths guided-style instead of field by field.
            OutlinedButton.icon(
              icon: const Icon(Icons.tune),
              label: const Text('Run First-Time Setup'),
              onPressed: () => showDialog(
                context: context,
                barrierDismissible: false,
                builder: (_) => const FirstRunSetupDialog(),
              ),
            ),
          ],
        ),
        const SizedBox(height: 30),

        // --- THEME STYLE ---
        // Two styles, each with its own accent swatch picker below:
        // Classic (flex_color_scheme, the default) and Auris (sci-fi HUD).
        // Dark/light stays on thsdae toolbar toggle.
        DropdownButtonFormField<String>(
          decoration: const InputDecoration(
            labelText: 'Theme Style',
            helperText:
                'Both styles use the accent color picked below. The sun/moon '
                'button still toggles dark & light.',
            border: OutlineInputBorder(),
          ),
          initialValue: provider.themeStyle,
          items: [
            _themeStyleItem('classic', 'Classic (Default)',
                RoomConfigApp.parseHexColor(provider.classicColor)),
            _themeStyleItem(
                'auris',
                'Auris (Sci-Fi)',
                RoomConfigApp.parseHexColor(provider.aurisColor,
                    fallback: const Color(0xFFF0A500))),
          ],
          onChanged: (val) {
            if (val != null) provider.updateSetting('themeStyle', val);
          },
        ),
        const SizedBox(height: 12),

        // --- ACCENT COLOR PICKER (swatches follow the selected style) ---
        Text(
            provider.themeStyle == 'auris'
                ? 'Auris Accent Color'
                : 'Classic Accent Color',
            style: Theme.of(context).textTheme.titleSmall),
        const SizedBox(height: 8),
        provider.themeStyle == 'auris'
            ? const AccentColorPicker(
                settingKey: 'aurisColor',
                swatches: RoomConfigApp.aurisSwatches)
            : const AccentColorPicker(
                settingKey: 'classicColor',
                swatches: RoomConfigApp.classicSwatches),
        const SizedBox(height: 16),

        // --- SECONDARY ELEMENT COLOR (Classic only; Auto = theme-derived).
        // Auris bakes its own slate secondary, so it has no picker here.
        if (provider.themeStyle == 'classic') ...[
          Text('Classic Secondary Color (other elements)',
              style: Theme.of(context).textTheme.titleSmall),
          const SizedBox(height: 4),
          Text(
            'Colors highlights, chips, and toggles. Auto derives it from the accent color.',
            style: Theme.of(context).textTheme.bodySmall,
          ),
          const SizedBox(height: 8),
          const AccentColorPicker(
              settingKey: 'classicSecondary',
              swatches: RoomConfigApp.classicSwatches,
              allowAuto: true),
        ],
        const SizedBox(height: 20),

        // --- TEXT SIZE ---
        // App-wide text scale, applied via the MediaQuery text scaler that
        // wraps the MaterialApp. Persisted like every other setting.
        Builder(builder: (context) {
          const Map<String, String> sizes = {
            '0.85': 'Small (85%)',
            '1.0': 'Normal (100%)',
            '1.15': 'Large (115%)',
            '1.3': 'Extra Large (130%)',
            '1.5': 'Huge (150%)',
          };
          // Match the stored double back to an option key; null (no
          // selection shown) if it was hand-set to something unlisted.
          final String? current = sizes.keys.firstWhere(
              (k) => double.parse(k) == provider.textScale,
              orElse: () => '');
          return DropdownButtonFormField<String>(
            decoration: const InputDecoration(
              labelText: 'Text Size',
              helperText: 'Scales all text in the app.',
              border: OutlineInputBorder(),
            ),
            initialValue: (current != null && current.isNotEmpty) ? current : null,
            items: sizes.entries
                .map((e) =>
                    DropdownMenuItem(value: e.key, child: Text(e.value)))
                .toList(),
            onChanged: (val) {
              if (val != null) provider.updateSetting('textScale', val);
            },
          );
        }),
        const SizedBox(height: 20),

        // --- DEVICE DEFAULTS ON LOAD ---
        // Load-time counterpart of ui_schema.json "device_defaults": also
        // fill missing baseline properties when opening an existing config.
        SwitchListTile(
          title: const Text('Fill missing device defaults when loading'),
          subtitle: const Text(
              'Adds properties from ui_schema.json "device_defaults" that a '
              'loaded config\'s devices are missing (e.g. DSP audio groups). '
              'Additions are listed in the load acknowledgement — nothing is '
              'saved until you export or apply.'),
          value: provider.fillDeviceDefaultsOnLoad,
          onChanged: (val) => provider.setFillDeviceDefaultsOnLoad(val),
        ),
        const SizedBox(height: 20),

        // Python Modules Path
        TextFormField(
          key: ValueKey(provider.modulesPath), // Forces UI to refresh when picked via dialog
          decoration: InputDecoration(
            labelText: 'Python Modules Path',
            // Blank = the "devices" sub-folder of the Root Folder
            hintText: provider.effectiveModulesPath,
            helperText: 'Blank = "devices" sub-folder of the Root Folder',
            border: const OutlineInputBorder(),
            suffixIcon: IconButton(
              icon: const Icon(Icons.folder),
              tooltip: 'Select Directory',
              onPressed: () async {
                String? selectedDirectory = await FilePicker.getDirectoryPath();
                if (selectedDirectory != null) {
                  provider.updateSetting('modulesPath', selectedDirectory);
                }
              },
            ),
          ),
          initialValue: provider.modulesPath,
          onChanged: (val) => provider.updateSetting('modulesPath', val),
        ),
        const SizedBox(height: 20),
        
        // Buildings JSON Path
        TextFormField(
          key: ValueKey(provider.buildingsFilePath),
          decoration: InputDecoration(
            labelText: 'Buildings JSON File Path',
            // Blank = buildings.json in the Root Folder
            hintText: provider.effectiveBuildingsFilePath,
            helperText: 'Blank = buildings.json in the Root Folder',
            border: const OutlineInputBorder(),
            suffixIcon: IconButton(
              icon: const Icon(Icons.file_open),
              tooltip: 'Select JSON File',
              onPressed: () async {
                FilePickerResult? result = await FilePicker.pickFiles(
                  type: FileType.custom, 
                  allowedExtensions: ['json']
                );
                if (result != null) {
                  // updateSetting reloads the buildings list itself
                  provider.updateSetting('buildingsFilePath', result.files.single.path!);
                }
              },
            ),
          ),
          initialValue: provider.buildingsFilePath,
          // updateSetting reloads the buildings list itself
          onChanged: (val) => provider.updateSetting('buildingsFilePath', val),
        ),
        const SizedBox(height: 20),

        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Default config.json Template Path
            Expanded(
              child: TextFormField(
                key: ValueKey(provider.templateFilePath),
                decoration: InputDecoration(
                  labelText: 'Default config.json Template Path',
                  // Blank = config.json in the Root Folder
                  hintText: provider.effectiveTemplateFilePath,
                  helperText: 'Blank = config.json in the Root Folder',
                  border: const OutlineInputBorder(),
                  suffixIcon: IconButton(
                    icon: const Icon(Icons.file_open),
                    tooltip: 'Select JSON File',
                    onPressed: () async {
                      FilePickerResult? result = await FilePicker.pickFiles(
                        type: FileType.custom, 
                        allowedExtensions: ['json']
                      );
                      if (result != null) {
                        provider.updateSetting('templateFilePath', result.files.single.path!);
                      }
                    },
                  ),
                ),
                initialValue: provider.templateFilePath,
                onChanged: (val) => provider.updateSetting('templateFilePath', val),
              ),
            ),
            const SizedBox(width: 16),
            SizedBox(
              height: 56, // Matches the height of the TextFormField
              child: ElevatedButton.icon(
                icon: const Icon(Icons.upload_file),
                label: const Text('Load Template'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.blue.shade700,
                  foregroundColor: Colors.white, // FIX: label/icon were unreadable in light mode
                ),
                onPressed: () async {
                  // Validates & registers the template only. The file is not
                  // opened into the editor until 'Create New Config' is pressed.
                  // A blank field validates the default: config.json in the
                  // Root Folder / working directory.
                  bool valid = await provider
                      .validateConfigTemplate(provider.effectiveTemplateFilePath);
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                      content: Text(valid
                          ? 'Template validated & saved as default. Use "Create New Config" to start from it.'
                          : 'No valid template at ${provider.effectiveTemplateFilePath} (missing or invalid JSON).'),
                      backgroundColor: valid ? Colors.green : Colors.red,
                    ));
                  }
                },
              ),
            ),
          ],
        ),
        const SizedBox(height: 20),

        // UI Schema (GUI field definitions) Path
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Expanded(
              child: TextFormField(
                key: ValueKey(provider.uiSchemaPath),
                decoration: InputDecoration(
                  labelText: 'UI Schema File Path (ui_schema.json)',
                  hintText: 'Blank = ui_schema.json in the Root Folder / next to the app',
                  helperText: 'Active schema: ${provider.uiSchema.source} — ${provider.uiSchema.fieldCount} field definitions',
                  border: const OutlineInputBorder(),
                  suffixIcon: IconButton(
                    icon: const Icon(Icons.file_open),
                    tooltip: 'Select JSON File',
                    onPressed: () async {
                      FilePickerResult? result = await FilePicker.pickFiles(
                        type: FileType.custom,
                        allowedExtensions: ['json'],
                      );
                      if (result != null) {
                        provider.updateSetting('uiSchemaPath', result.files.single.path!);
                      }
                    },
                  ),
                ),
                initialValue: provider.uiSchemaPath,
                onChanged: (val) => provider.updateSetting('uiSchemaPath', val),
              ),
            ),
            const SizedBox(width: 16),
            SizedBox(
              height: 56, // Matches the height of the TextFormField
              child: ElevatedButton.icon(
                icon: const Icon(Icons.refresh),
                label: const Text('Reload Schema'),
                onPressed: () async {
                  // Pull in edits made to ui_schema.json without restarting
                  await provider.loadUiSchema();
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                      content: Text('Schema reloaded: ${provider.uiSchema.source} '
                          '(${provider.uiSchema.fieldCount} field definitions)'),
                    ));
                  }
                },
              ),
            ),
          ],
        ),
        const SizedBox(height: 20),

        // Legacy Key Map (key_map.json) Path
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Expanded(
              child: TextFormField(
                key: ValueKey(provider.keyMapPath),
                decoration: InputDecoration(
                  labelText: 'Legacy Key Map File Path (key_map.json)',
                  hintText: 'Blank = key_map.json in the Root Folder / next to the app',
                  helperText: 'Active map: ${provider.keyMap.source} — ${provider.keyMap.ruleCount} rules. '
                      'Applied automatically when a config is loaded.',
                  border: const OutlineInputBorder(),
                  suffixIcon: IconButton(
                    icon: const Icon(Icons.file_open),
                    tooltip: 'Select JSON File',
                    onPressed: () async {
                      FilePickerResult? result = await FilePicker.pickFiles(
                        type: FileType.custom,
                        allowedExtensions: ['json'],
                      );
                      if (result != null) {
                        provider.updateSetting('keyMapPath', result.files.single.path!);
                      }
                    },
                  ),
                ),
                initialValue: provider.keyMapPath,
                onChanged: (val) => provider.updateSetting('keyMapPath', val),
              ),
            ),
            const SizedBox(width: 16),
            SizedBox(
              height: 56, // Matches the height of the TextFormField
              child: ElevatedButton.icon(
                icon: const Icon(Icons.refresh),
                label: const Text('Reload Key Map'),
                onPressed: () async {
                  // Pull in edits made to key_map.json without restarting
                  await provider.loadKeyMap();
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                      content: Text('Key map reloaded: ${provider.keyMap.source} '
                          '(${provider.keyMap.ruleCount} rules)'),
                    ));
                  }
                },
              ),
            ),
          ],
        ),
        const SizedBox(height: 20),

        // Processors JSON Path
        TextFormField(
          key: ValueKey(provider.processorsFilePath),
          decoration: InputDecoration(
            labelText: 'Processors JSON File Path',
            // Blank = processors.json in the Root Folder; read automatically on boot
            hintText: provider.effectiveProcessorsFilePath,
            helperText: 'Blank = processors.json in the Root Folder. Read automatically on startup.',
            border: const OutlineInputBorder(),
            suffixIcon: IconButton(
              icon: const Icon(Icons.file_open),
              tooltip: 'Select JSON File',
              onPressed: () async {
                FilePickerResult? result = await FilePicker.pickFiles(
                  type: FileType.custom, 
                  allowedExtensions: ['json']
                );
                if (result != null) {
                  // updateSetting reloads the processors list itself
                  provider.updateSetting('processorsFilePath', result.files.single.path!);
                }
              },
            ),
          ),
          initialValue: provider.processorsFilePath,
          // updateSetting reloads the processors list itself
          onChanged: (val) => provider.updateSetting('processorsFilePath', val),
        ),
        const SizedBox(height: 20),
        
        Align(
          alignment: Alignment.centerLeft,
          child: ElevatedButton.icon(
            icon: const Icon(Icons.sync),
            label: const Text('Load Processors Data'),
            onPressed: () => provider.loadProcessorsList(),
          ),
        ),
        const SizedBox(height: 20),

        // Template Root Path
        TextFormField(
          key: ValueKey(provider.rootFolderPath),
          decoration: InputDecoration(
            labelText: 'Root Folder Path (default base for all blank paths above)',
            hintText: provider.effectiveRootFolder,
            helperText: 'Blank = the app\'s working directory. Blank paths above default to files in this folder '
                '(config.json, processors.json, buildings.json, ui_schema.json, key_map.json, and the "devices" modules sub-folder).',
            helperMaxLines: 3,
            border: const OutlineInputBorder(),
            suffixIcon: IconButton(
              icon: const Icon(Icons.folder),
              tooltip: 'Select Directory',
              onPressed: () async {
                String? selectedDirectory = await FilePicker.getDirectoryPath();
                if (selectedDirectory != null) {
                  provider.updateSetting('rootFolderPath', selectedDirectory);
                }
              },
            ),
          ),
          initialValue: provider.rootFolderPath,
          onChanged: (val) => provider.updateSetting('rootFolderPath', val),
        ),
        const SizedBox(height: 20),

        Text('Active Deployment Target', style: Theme.of(context).textTheme.titleLarge),
        const SizedBox(height: 20),
        
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Expanded(
              child: DropdownButtonFormField<String>(
                decoration: const InputDecoration(
                  labelText: 'Select Room Deployment',
                  border: OutlineInputBorder(),
                ),
                value: provider.selectedProcessor?['roomId']?.toString(),
                items: provider.processors.map((proc) {
                  return DropdownMenuItem<String>(
                    value: proc['roomId']?.toString(),
                    child: Text("${proc['roomName']} (ID: ${proc['roomId']})"),
                  );
                }).toList(),
                onChanged: (val) {
                  if (val != null) {
                    final selected = provider.processors.firstWhere(
                      (p) => p['roomId']?.toString() == val,
                      orElse: () => <String, dynamic>{},
                    );
                    if (selected.isNotEmpty) {
                      provider.selectProcessor(selected);
                    }
                  }
                },
              ),
            ),
            const SizedBox(width: 16),
            Padding(
              padding: const EdgeInsets.only(top: 4.0),
              child: IconButton(
                icon: const Icon(Icons.clear),
                tooltip: 'Clear Active Room',
                onPressed: () => provider.selectProcessor(null), 
              ),
            ),
          ],
        ),
      ],
    );
  }
}

/// A dialog that handles both SFTP directions with the processor:
///  - Upload:   pushes the in-memory config to /config.json on the processor
///  - Download: pulls /config.json, backs it up, prompts for a new working file
/// The IP is pre-filled from the Active Deployment Target (App Config tab);
/// when no room is selected, the user is prompted for it as before.
class ProcessorSftpDialog extends StatefulWidget {
  final bool isUpload;
  const ProcessorSftpDialog({Key? key, required this.isUpload}) : super(key: key);

  @override
  State<ProcessorSftpDialog> createState() => _ProcessorSftpDialogState();
}

class _ProcessorSftpDialogState extends State<ProcessorSftpDialog> {
  final TextEditingController _ipController = TextEditingController();
  final TextEditingController _passController = TextEditingController();
  
  String _statusText = '';
  bool _isBusy = false;
  String _targetRoomName = '';

  /// Optional additional file to push alongside config.json (upload mode
  /// only). Stays blank unless the user picks one — e.g. Whereused.csv.
  String _extraFilePath = '';

  @override
  void initState() {
    super.initState();
    // Pre-fill from the Active Deployment Target if one is selected
    final provider = context.read<AppStateProvider>();
    final ip = provider.selectedProcessorIp;
    if (ip.isNotEmpty) {
      _ipController.text = ip;
      _targetRoomName = provider.selectedProcessor?['roomName']?.toString() ?? '';
    }
    _statusText = widget.isUpload
        ? 'Enter processor details to upload config.json'
        : 'Enter processor details to download config.json';
  }

  @override
  void dispose() {
    _ipController.dispose();
    _passController.dispose();
    super.dispose();
  }

  Future<void> _startTransfer() async {
    // Basic validation
    if (_ipController.text.isEmpty || _passController.text.isEmpty) {
      setState(() => _statusText = "Error: IP and Password are required.");
      return;
    }

    setState(() {
      _isBusy = true;
      _statusText = "Initializing...";
    });

    final provider = context.read<AppStateProvider>();
    
    bool success;
    if (widget.isUpload) {
      success = await provider.uploadConfigToProcessor(
        ipAddress: _ipController.text.trim(),
        password: _passController.text,
        onStatusUpdate: (status) => setState(() => _statusText = status),
        // Blank = upload only config.json (the default behavior)
        extraFilePath: _extraFilePath.isNotEmpty ? _extraFilePath : null,
      );
    } else {
      success = await provider.downloadConfigFromProcessor(
        ipAddress: _ipController.text.trim(),
        password: _passController.text,
        onStatusUpdate: (status) {
          if (mounted) setState(() => _statusText = status);
        },
      );
    }

    if (!mounted) return;
    setState(() => _isBusy = false);

    if (success) {
      if (widget.isUpload) {
        // Automatically close the dialog after a brief delay on success
        Future.delayed(const Duration(seconds: 2), () {
          if (mounted) Navigator.of(context).pop();
        });
      } else {
        // Close immediately and signal success so the audit dialog can be shown
        Navigator.of(context).pop(true);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(widget.isUpload ? 'Direct SFTP Upload' : 'Download Config from Processor'),
      content: SizedBox(
        width: 400,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            if (_targetRoomName.isNotEmpty)
              Padding(
                padding: const EdgeInsets.only(bottom: 12.0),
                child: Text(
                  'Active Deployment Target: $_targetRoomName',
                  style: const TextStyle(fontWeight: FontWeight.bold),
                ),
              ),
            TextFormField(
              controller: _ipController,
              decoration: const InputDecoration(
                labelText: 'Processor IP / Hostname',
                border: OutlineInputBorder(),
              ),
              enabled: !_isBusy,
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _passController,
              obscureText: true,
              decoration: const InputDecoration(
                labelText: 'Admin Password',
                border: OutlineInputBorder(),
              ),
              enabled: !_isBusy,
            ),

            // --- ADDITIONAL FILE (upload only, optional) ---
            // Leave blank to upload just config.json. Typically used to push
            // a Whereused.csv along with the config in one connection.
            if (widget.isUpload) ...[
              const SizedBox(height: 20),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.grey.shade600),
                  borderRadius: BorderRadius.circular(4),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('Additional File (optional)',
                        style: Theme.of(context).textTheme.titleSmall),
                    const SizedBox(height: 4),
                    Text(
                      _extraFilePath.isEmpty
                          ? 'None selected — only config.json will be uploaded.'
                          : 'Will also upload: ${_extraFilePath.split(Platform.pathSeparator).last}',
                      style: TextStyle(
                        fontSize: 12,
                        color: _extraFilePath.isEmpty ? Colors.grey : null,
                        fontStyle: _extraFilePath.isEmpty ? FontStyle.italic : null,
                      ),
                      overflow: TextOverflow.ellipsis,
                    ),
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        OutlinedButton.icon(
                          icon: const Icon(Icons.attach_file, size: 18),
                          label: Text(_extraFilePath.isEmpty ? 'Add File' : 'Change File'),
                          onPressed: _isBusy
                              ? null
                              : () async {
                                  // Any file type: Whereused.csv is typical,
                                  // but module .py files etc. work too.
                                  final result = await FilePicker.pickFiles();
                                  if (result != null && mounted) {
                                    setState(() => _extraFilePath =
                                        result.files.single.path ?? '');
                                  }
                                },
                        ),
                        if (_extraFilePath.isNotEmpty) ...[
                          const SizedBox(width: 8),
                          TextButton.icon(
                            icon: const Icon(Icons.clear, size: 18),
                            label: const Text('Clear'),
                            onPressed: _isBusy
                                ? null
                                : () => setState(() => _extraFilePath = ''),
                          ),
                        ],
                      ],
                    ),
                  ],
                ),
              ),
            ],
            const SizedBox(height: 24),
            
            // Status read-out container (contrast-safe in both themes)
            Builder(builder: (context) {
              final bool isDark = Theme.of(context).brightness == Brightness.dark;
              final Color boxColor = isDark ? Colors.black26 : const Color(0xFFF0F0F0);
              final TextStyle statusStyle = TextStyle(
                fontFamily: 'monospace',
                color: isDark ? Colors.white70 : Colors.black87,
              );
              return Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: boxColor,
                  borderRadius: BorderRadius.circular(4),
                  border: isDark ? null : Border.all(color: Colors.grey.shade400),
                ),
                height: 80,
                alignment: Alignment.centerLeft,
                child: _isBusy && _statusText.contains("Connecting")
                    ? Row(
                        children: [
                          const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2)),
                          const SizedBox(width: 16),
                          Expanded(child: Text(_statusText, style: statusStyle)),
                        ],
                      )
                    : Text(_statusText, style: statusStyle),
              );
            }),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: _isBusy ? null : () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        ElevatedButton.icon(
          icon: Icon(widget.isUpload ? Icons.cloud_upload : Icons.cloud_download),
          label: Text(widget.isUpload ? 'Upload' : 'Download'),
          onPressed: _isBusy ? null : _startTransfer,
        ),
      ],
    );
  }
}

/// ============================================================================
///  FIRST-RUN SETUP DIALOG
/// ============================================================================
///  Shown ONCE on the very first launch (before any settings are saved),
///  asking where each external file is located. Finishing (or skipping)
///  persists 'initialSetupComplete', so the check is bypassed on every
///  later launch. Can be re-opened any time from the App Config tab.
///
///  Pick the Root Folder first: every file found inside it is detected
///  automatically (green check). Browse individually only for files that
///  live somewhere else. Every Browse choice is saved immediately.
/// ============================================================================
class FirstRunSetupDialog extends StatelessWidget {
  const FirstRunSetupDialog({Key? key}) : super(key: key);

  Future<void> _finish(BuildContext context, AppStateProvider provider) async {
    await provider.completeFirstRunSetup();
    if (context.mounted) Navigator.of(context).pop();
  }

  @override
  Widget build(BuildContext context) {
    // watch: rows refresh live as paths are picked (updateSetting notifies)
    final provider = context.watch<AppStateProvider>();

    final bool rootExists = Directory(provider.effectiveRootFolder).existsSync();
    final bool templateExists = File(provider.effectiveTemplateFilePath).existsSync();
    final bool processorsExists = File(provider.effectiveProcessorsFilePath).existsSync();
    final bool buildingsExists = File(provider.effectiveBuildingsFilePath).existsSync();
    final bool schemaExists = File(provider.effectiveUiSchemaPath).existsSync();
    final bool keyMapExists = File(provider.effectiveKeyMapPath).existsSync();
    final bool modulesExists = Directory(provider.effectiveModulesPath).existsSync();

    return AlertDialog(
      title: Row(
        children: const [
          Icon(Icons.tune),
          SizedBox(width: 10),
          Expanded(child: Text('First-Time Setup — Locate Your Files')),
        ],
      ),
      content: SizedBox(
        width: 680,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Pick the Root Folder first — every file found inside it is detected '
                'automatically. Use Browse on any row where a file lives somewhere else. '
                'Green = found at the shown location, red = not found (you can still '
                'finish and set it later in App Config). Choices are saved immediately, '
                'and this dialog will not appear again after you finish.',
              ),
              const SizedBox(height: 18),
              // --- PREFERRED ACCENT COLOR ---
              // Follows the ACTIVE theme style, so re-running setup while
              // Auris is selected offers the Auris swatches (which actually
              // apply) instead of the Classic ones. Saved instantly, and
              // changeable any time under App Config > Theme Style.
              const Text('Preferred accent color',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
              const SizedBox(height: 4),
              Text(
                provider.themeStyle == 'auris'
                    ? 'Pick the accent for the Auris theme. You can change it '
                        'later in App Config.'
                    : 'Pick the color the app theme is built around. You can '
                        'change it later in App Config.',
                style: Theme.of(context).textTheme.bodySmall,
              ),
              const SizedBox(height: 10),
              provider.themeStyle == 'auris'
                  ? const AccentColorPicker(
                      settingKey: 'aurisColor',
                      swatches: RoomConfigApp.aurisSwatches)
                  : const AccentColorPicker(
                      settingKey: 'classicColor',
                      swatches: RoomConfigApp.classicSwatches),
              const Divider(height: 24),
              _pathRow(context, provider,
                  label: 'Root Folder (default base for everything below)',
                  value: provider.effectiveRootFolder,
                  exists: rootExists,
                  isDirectory: true,
                  settingKey: 'rootFolderPath'),
              const Divider(height: 18),
              _pathRow(context, provider,
                  label: 'Template config.json',
                  value: provider.effectiveTemplateFilePath,
                  exists: templateExists,
                  settingKey: 'templateFilePath'),
              _pathRow(context, provider,
                  label: 'processors.json (deployment targets — read on startup)',
                  value: provider.effectiveProcessorsFilePath,
                  exists: processorsExists,
                  settingKey: 'processorsFilePath'),
              _pathRow(context, provider,
                  label: 'buildings.json (building names & abbreviations)',
                  value: provider.effectiveBuildingsFilePath,
                  exists: buildingsExists,
                  settingKey: 'buildingsFilePath'),
              _pathRow(context, provider,
                  label: 'ui_schema.json (GUI field definitions — optional)',
                  value: provider.effectiveUiSchemaPath,
                  exists: schemaExists,
                  settingKey: 'uiSchemaPath'),
              _pathRow(context, provider,
                  label: 'key_map.json (legacy key translation — optional)',
                  value: provider.effectiveKeyMapPath,
                  exists: keyMapExists,
                  settingKey: 'keyMapPath'),
              _pathRow(context, provider,
                  label: 'Python modules folder (default: "devices" sub-folder)',
                  value: provider.effectiveModulesPath,
                  exists: modulesExists,
                  isDirectory: true,
                  settingKey: 'modulesPath'),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          // Skipping also completes setup, so the app never nags again;
          // everything runs on the defaults shown above.
          onPressed: () => _finish(context, provider),
          child: const Text('Skip — use the defaults shown'),
        ),
        ElevatedButton.icon(
          icon: const Icon(Icons.check),
          label: const Text('Finish Setup'),
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.green.shade700,
            foregroundColor: Colors.white,
          ),
          onPressed: () => _finish(context, provider),
        ),
      ],
    );
  }

  /// One row: found/missing icon, label, resolved path, Browse button.
  Widget _pathRow(BuildContext context, AppStateProvider provider,
      {required String label,
      required String value,
      required bool exists,
      bool isDirectory = false,
      required String settingKey}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Icon(
            exists ? Icons.check_circle : Icons.error_outline,
            color: exists ? Colors.green : Colors.red.shade400,
            size: 20,
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(label,
                    style: const TextStyle(
                        fontWeight: FontWeight.bold, fontSize: 13)),
                Text(
                  value,
                  style: Theme.of(context).textTheme.bodySmall,
                  overflow: TextOverflow.ellipsis,
                ),
              ],
            ),
          ),
          const SizedBox(width: 8),
          TextButton.icon(
            icon: Icon(isDirectory ? Icons.folder_open : Icons.file_open,
                size: 18),
            label: const Text('Browse'),
            onPressed: () async {
              if (isDirectory) {
                String? dir = await FilePicker.getDirectoryPath();
                if (dir != null) {
                  // Persisted immediately; updateSetting also reloads
                  // whatever depends on this path.
                  provider.updateSetting(settingKey, dir);
                }
              } else {
                FilePickerResult? result = await FilePicker.pickFiles(
                  type: FileType.custom,
                  allowedExtensions: ['json'],
                );
                if (result != null) {
                  provider.updateSetting(
                      settingKey, result.files.single.path!);
                }
              }
            },
          ),
        ],
      ),
    );
  }
}
